services:
  - type: web
    name: final-one
    env: python
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: GOOGLE_CHROME_BIN
        value: /usr/bin/google-chrome
