services:
  - type: web
    name: attendance-flask
    env: python
    buildCommand: |
      apt-get update && apt-get install -y chromium
      pip install -r requirements.txt
    startCommand: gunicorn grok.app:app
    plan: free
